[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  NODE_OPTIONS = "--max_old_space_size=4096"

[build]
  command = "npx pnpm i --store=../node_modules/.pnpm-store && cd .. && pnpm run deploy"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/play/*"
  to = "/play/index.html"
  status = 200

[[redirects]]
  from = "https://unocss.antfu.me/:slug"
  to = "https://uno.antfu.me/play/:slug"
  status = 302
