[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"
  NODE_OPTIONS = "--max_old_space_size=4096"

[build]
  publish = "dist"
  command = "cd .. && npx pnpm i --store=./node_modules/.pnpm-store && pnpm run deploy && cd interactive"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/play/*"
  to = "/play/index.html"
  status = 200

[[redirects]]
  from = "https://unocss.antfu.me/*"
  to = "https://uno.antfu.me/play/:splat"
  status = 302
